name: flutter_celik_api
description: CelikAPI (Serbian ID Reader) written from scratch. Works on Windows/Linux/MacOS.

# publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1+2
repository: https://github.com/web-ez/flutter_celik_api

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  aes_crypt_null_safe: ^2.0.2
  asn1lib: ^1.1.0
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  flutter_pcsc: ^0.0.4
  x509: ^0.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.21.1
